heroku:
  stage: deploy
  only:
    - main
  script:
    - git config --global user.email "ankit.srivastava.17.1@mountblue.tech"
    - git config --global user.name "Ankit15708"
    - rm -rf .git
    - git init
    - git add .
    - git commit -m "initial commit"
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/hackernewzclone.git
    - git push -f heroku master
